### ISSUE TITLE
Peer Forwarder Plugin

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#200]
The trace analytics feature is the first pipeline that Data Prepper will offer. This feature is requires spans belonging to the same trace workflow to be routed to the same host so we can process and make decision on the entire trace workflow.

The end state is we have a processor plugin,

```
processor:
    - peer_forwarder:
       discovery.mode: [] 
       peer.host: []
       time_out: 300
       span_agg_count: 48 
```

The plugin should have an option to auto discovery/list of peers and support the routing.

Items:

- [x] consistent hashing algorithm
- [x] Discovery approach
- [x] Integrate with metrics(Austin already has the abstract classes)
   - [x] Inherit common metrics abstract classes
   - [x] Add custom metrics by introducing timer, counter, etc in constructor
- [x] Integration tests that ensure we are routing them correctly and detecting service map relationship.
   - [x] Update e2e test to include at least 2 data prepper instances to receive traces.
   - [x] Integration test for discovery mode #224 
- [x] SSL/TLS support
- [x] Documentation on how to configure various options
