### ISSUE TITLE
Combine pipelines yaml and data-prepper server yaml files?

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#439]
Presently Data Prepper requires both a pipelines.yaml and a data-prepper.yaml (server config) file to be provided when starting up. 

* Pipelines is required because there are no default pipelines.  
* The server config file is required because Data Prepper defaults to TLS enabled but does not have a default key file to use.

Can we combine this into one main configuration file, e.g.
```yaml
server:
    ssl: false
pipelines:
    entry_pipeline:
        ...
```
