### ISSUE TITLE
Cast error when sending traces through data prepper.

### ISSUE THREAD

**Issue by jamiegs** [opendistro-for-elasticsearch/data-prepper#464]
**Describe the bug**

I've got the OpenTelemetry collector sending traces to the data prepper.  

I'm receiving service map data, but due to the following error the trace data isn't making it's way to my elasticsearch server,

```
java.lang.ClassCastException: class io.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest cannot be cast to class java.lang.String (io.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	com.amazon.dataprepper.plugins.prepper.StringPrepper.execute(StringPrepper.java:39) ~[data-prepper.jar:0.8.0-beta]
	com.amazon.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:57) [data-prepper.jar:0.8.0-beta]
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**To Reproduce**
    - Configure pipeline as follows:   OpenTelemetry Dotnet SDK -> OpenTelemetry-collector-contrib -> ALB load balancer -> Data Prepper -> AWS Elasticsearch service
     - Produce traces
     - View error

**Expected behavior**
    I'm expecting that the traces will be exported to the Elasticsearch server and no errors will be in the data prepper logs .

**Screenshots**

**Environment (please complete the following information):**
OpenTelemetry SDK:
    Version: v1.0.1
    Platform: dotnet
    [OpenTelemetry Dotnet SDK](https://www.nuget.org/packages/OpenTelemetry/1.0.1) 
    
Elasticsearch server: 
    Hosted in AWS Elasticsearch service
    Version: R20210201-P2
    
OpenTelemetry Collector:
   opentelemetry-collector-contrib 
   Version: 0.22.0
   running within Docker on ECS
   
Data Prepper:
   Version: 0.8.0-beta
   running within Docker on ECS Fargate
   
**Additional context**

**Comment by wrijeff** [comment]
Thanks @jamiegs for the bug report. From the stacktrace it looks like an OTelTraceSource is sending data to a StringPrepper. If so then there's a runtime mismatch of source-output and prepper-input.

* OTelTraceSource: outputs records containing ExportTraceServiceRequest objects
* StringPrepper: expects records containing String objects

To fix the immediate issue, you'd just need to remove the StringPrepper from the pipelines yaml file. Check out [trace_setup.md](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/main/docs/readme/trace_setup.md) for a sample yaml file configured specifically for the trace analytics usecase. Since you're using Amazon Elasticsearch Service, just replace the 2 ES sink blocks with something like:
```yaml
  sink:
    - elasticsearch:
        hosts: [ "https://your-domain.us-east-1.es.amazonaws.com" ]
        aws_sigv4: true
        aws_region: "us-east-1"
        trace_analytics_raw: true
```
and
```yaml
  sink:
    - elasticsearch:
        hosts: [ "https://your-domain.us-east-1.es.amazonaws.com" ]
        aws_sigv4: true
        aws_region: "us-east-1"
        trace_analytics_service_map: true
```

For a mid-term fix, I'll create an issue to update the documentation regarding inputs and outputs (I can see it could definitely be improved). And for the long-term, it'd be nice if DP could parse the config file on startup and detect if there are any config issues like these.

Let me know if you're still running into issues even after updating the pipelines yaml.
