### ISSUE TITLE
Integration with jaeger operator

### ISSUE THREAD

**Issue by serg-bs** [opendistro-for-elasticsearch/data-prepper#940]
**Is your feature request related to a problem? Please describe.**
I install jaeger operator, backend 

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
    name: simple-prod
spec:
    strategy: production
    ingress:
        enabled: false
    agent:
      strategy: DaemonSet
    storage:
        type: elasticsearch
        options:
            es:
                server-urls: http://opendistro-elastic:9200
                username:  username
                password: password
```
[Supported storage backend](https://www.jaegertracing.io/docs/1.28/#technical-specs) could not be data prepper
May be some [Storage plugin](https://www.jaegertracing.io/docs/1.28/operator/#storage-plugin) should we use in this case?

How to set up data-prepper in such cases ?
